version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/kampus-server

permissions:
  - object: scripts/start-server.sh
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 60
      runas: ec2-user